version: 1.0.0-build.{build}
image: Visual Studio 2019
environment:
  MYGET_FEED: https://www.myget.org/F/cake-tasks/api/v2/package
  MYGET_APIKEY:
    secure: 3tEiaoqZlTJcJkAX+3wWyp3mbCYuJpALEFzTEaum6ACiXbWgsa1kWYGBi3TUFY7c
  MYGET_SYMBOLS_FEED: https://www.myget.org/F/cake-tasks/symbols/api/v2/package
  MYGET_SYMBOLS_APIKEY:
    secure: 3tEiaoqZlTJcJkAX+3wWyp3mbCYuJpALEFzTEaum6ACiXbWgsa1kWYGBi3TUFY7c
build_script:
- pwsh: ./build.ps1 -target ci -ci appveyor
- pwsh: tree ./tools
deploy_script:
- pwsh: ./build.ps1 -target DeployPackages
- pwsh: ./.build/deploy.ps1
